[project]
name = 'Blockchain-Based-Financial-Planning-Budgeting-and-Forecasting'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cost-tracking]
path = 'contracts/cost-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
